name: CFN -> ThreatModel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
   FILENAME: D:\a\tmcreate\tmcreate\iacassist_architecture_poc.json
   MODELNAME: iacassist_architecture_poc2.json

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download/Unzip TM CLI
        run: |
          Invoke-WebRequest -Uri "https://drive.google.com/uc?export=download&id=1W2OkfTlEt0JPLwV6gAdbA-Rb-tHqZuHJ" -OutFile tm_runfiles.zip
          Expand-Archive -LiteralPath tm_runfiles.zip -DestinationPath .\tmrunfiles

      - name: Create Threat Model
        working-directory: .\tmrunfiles
        run: .\tmcreate submit_cfn --modelname "$env:MODELNAME" --file "$env:FILENAME" --apikey ${{secrets.TM_APIKEY}}
        
      - name: Store SARIF results as Build Artifact
        uses: actions/upload-artifact@v1
        with:
          name: IAC_SARIF_Results
          path: .\tmrunfiles\results.sarif

      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: .\tmrunfiles\results.sarif
          
