name: CFN -> ThreatModel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
   FILENAME: D:\a\tmcreate\tmcreate\WebServerEIPCfn_Secure.json
   MODELNAME: WebServerEIPCfn_Secure

jobs:
  build:
    runs-on: windows-2022

    steps:
          # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'javascript'
      - uses: actions/checkout@v2

      - name: Download/Unzip TM CLI
        run: |
          Invoke-WebRequest -Uri "https://drive.google.com/uc?id=1jeeTJ-LQyHkijYn589lhmo9Ae0NcUUfX&export=download" -OutFile tm_runfiles.zip
          Expand-Archive -LiteralPath tm_runfiles.zip -DestinationPath .\tmrunfiles

      - name: Create Threat Model
        working-directory: .\tmrunfiles
        run: .\tmcreate submit_cfn --modelname "$env:MODELNAME" --file "$env:FILENAME" --apikey ${{secrets.TM_APIKEY}}
        
      - name: Store SARIF results as Build Artifact
        uses: actions/upload-artifact@v1
        with:
          name: IAC_SARIF_Results
          path: .\tmrunfiles\WebServerEIPCfn_Secure.sarif

      - uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: .\tmrunfiles\WebServerEIPCfn_Secure.sarif
          
      #- name: Perform CodeQL Analysis
      #  uses: github/codeql-action/analyze@v1
