name: CFN -> ThreatModel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
   FILENAME: D:\a\tmcreate\tmcreate\cfn_complex.json
   MODELNAME: GitHubAction_CFN_Complex
   TM_FQDN: demo.threatmodeler.us

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Download/Unzip TM CLI
        run: |
          Invoke-WebRequest -Uri "https://drive.google.com/uc?export=download&id=1W2OkfTlEt0JPLwV6gAdbA-Rb-tHqZuHJ" -OutFile tm_runfiles.zip
          Expand-Archive -LiteralPath tm_runfiles.zip -DestinationPath .\tmrunfiles

      - name: Create Threat Model
        working-directory: .\tmrunfiles
        run: .\tmcreate submitcfn --modelname $MODELNAME --file $FILENAME --fqdn $TM_FQDN --un ${{secrets.DEMO_UN}} --pw '${{secrets.DEMO_PW}}'
        
